pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
        maven { url "https://artifactory.appodeal.com/appodeal-public/" }
        maven { url "https://repository.liferay.com/nexus/content/groups/public/" }
    }
}

include ':app', ':domain', ':data', ':device'
