package com.sedsoftware.yaptalker.features

object NavigationScreens {
  const val NEWS_SCREEN = "NEWS_SCREEN"
  const val FORUMS_LIST_SCREEN = "FORUMS_LIST_SCREEN"
  const val CHOSEN_FORUM_SCREEN = "CHOSEN_FORUM_SCREEN"
  const val CHOSEN_TOPIC_SCREEN = "CHOSEN_TOPIC_SCREEN"
  const val USER_PROFILE_SCREEN = "USER_PROFILE_SCREEN"
  const val AUTHORIZATION_SCREEN = "AUTHORIZATION_SCREEN"
  const val SETTINGS_SCREEN = "SETTINGS_SCREEN"
  const val ADD_MESSAGE_SCREEN = "ADD_MESSAGE_SCREEN"
}
