apply plugin: 'java'
apply plugin: 'kotlin'

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_1_8
    }
}

dependencies {
    def domainDependencies = rootProject.ext.domainDependencies
    def domainTestDependencies = rootProject.ext.domainTestDependencies

    implementation domainDependencies.kotlin
    implementation domainDependencies.javax
    implementation domainDependencies.rxJava
    implementation domainDependencies.rxKotlin

    testImplementation domainTestDependencies.junit
}

