plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.parcelize)
    alias(libs.plugins.kotlin.kapt)
    alias(libs.plugins.firebase.crashlytics)
    alias(libs.plugins.google.services)
}

android {
    def globalConfiguration = rootProject.extensions.getByName("ext")

    namespace "com.sedsoftware.yaptalker"
    compileSdk globalConfiguration["compileSdkVersion"]

    defaultConfig {
        minSdk globalConfiguration["minSdkVersion"]
        targetSdk globalConfiguration["targetSdkVersion"]
        applicationId globalConfiguration["androidApplicationId"]
        versionCode globalConfiguration["androidVersionCode"]
        versionName globalConfiguration["androidVersionName"]
        testInstrumentationRunner globalConfiguration["testInstrumentationRunner"]
        testApplicationId globalConfiguration["testApplicationId"]
        flavorDimensions "variant"
        resConfigs "en", "ru"
    }
    productFlavors {
        dev {
            dimension "variant"
            multiDexEnabled true
        }
        prod {
            dimension "variant"
        }
    }
    signingConfigs {
        release {
            storeFile file(RELEASE_STORE_FILE)
            storePassword RELEASE_STORE_PASSWORD
            keyAlias RELEASE_KEY_ALIAS
            keyPassword RELEASE_KEY_PASSWORD
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
            proguardFiles fileTree('proguard').asList().toArray()
        }
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility = 1.8
        targetCompatibility = 1.8
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }

    buildFeatures {
        viewBinding true
        buildConfig true
    }

    lint {
        disable 'Instantiatable'
    }
}

dependencies {
    implementation project(':domain')
    implementation project(':data')
    implementation project(':device')

    implementation libs.kotlin.stdlib.jdk8
    implementation libs.androidx.core.ktx

    implementation libs.room.runtime
    kapt libs.room.compiler

    implementation libs.androidx.appcompat
    implementation libs.androidx.preference
    implementation libs.androidx.legacy.preference.v14
    implementation libs.androidx.cardview
    implementation libs.android.material
    implementation libs.androidx.recyclerview
    implementation libs.androidx.constraintlayout

    implementation libs.dagger
    implementation libs.dagger.android
    implementation libs.dagger.android.support
    implementation libs.moxy
    implementation libs.moxy.android
    implementation libs.moxy.appcompat

    implementation libs.rxjava
    implementation libs.rxandroid
    implementation libs.rxkotlin
    implementation libs.rxrelay
    implementation libs.rxlint
    implementation libs.rxbinding.kotlin
    implementation libs.rxbinding.appcompat
    implementation libs.rxbinding.recyclerview
    implementation libs.rxbinding.support
    implementation libs.autodispose
    implementation libs.autodispose.kotlin

    implementation libs.gson
    implementation libs.retrofit
    implementation libs.retrofit.adapter.rxjava2
    implementation libs.retrofit.converter.gson
    implementation libs.retrofit.converter.scalars
    implementation libs.retrofit.converter.jspoon
    implementation libs.okhttp
    implementation libs.okhttp.logging.interceptor
    implementation libs.persistent.cookie.jar
    implementation libs.picasso
    implementation libs.glide
    implementation libs.glide.okhttp3
    kapt libs.glide.compiler

    implementation libs.material.values
    implementation(libs.materialdrawer) { transitive = true }
    implementation libs.material.chip
    implementation libs.flexbox
    implementation libs.iconics.core
    implementation libs.iconics.views
    implementation libs.community.material.typeface
    implementation libs.typeicons.typeface
    implementation libs.material.dialogs.core
    implementation libs.material.dialogs.commons
    implementation libs.photoview
    implementation libs.markwon
    implementation libs.swipe.refresh.bottom

    kapt libs.dagger.compiler
    kapt libs.dagger.android.compiler
    kapt libs.moxy.compiler

    testImplementation libs.junit

    implementation platform(libs.firebase.bom)
    implementation libs.firebase.analytics
    implementation libs.firebase.crashlytics

    implementation libs.timber

    implementation libs.stetho
}
