plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.kapt)
}

android {
    def globalConfiguration = rootProject.extensions.getByName("ext")

    namespace "com.sedsoftware.yaptalker.data"
    compileSdk globalConfiguration["compileSdkVersion"]

    defaultConfig {
        minSdk globalConfiguration["minSdkVersion"]
        targetSdk globalConfiguration["targetSdkVersion"]
        versionCode globalConfiguration["androidVersionCode"]
        versionName globalConfiguration["androidVersionName"]

        testInstrumentationRunner globalConfiguration["testInstrumentationRunner"]
        flavorDimensions "variant"
        resConfigs "en", "ru"
    }
    productFlavors {
        dev {
            dimension "variant"
        }
        prod {
            dimension "variant"
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    buildTypes.each {
        it.buildConfigField 'String', 'VK_ACCESS_TOKEN', VK_ACCESS_TOKEN
        it.buildConfigField 'int', 'VERSION_CODE', "${globalConfiguration["androidVersionCode"]}"
        it.buildConfigField 'String', 'VERSION_NAME', "\"${globalConfiguration["androidVersionName"]}\""
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = "1.8"
    }
    buildFeatures {
        buildConfig true
    }
}

dependencies {
    implementation project(':domain')

    implementation libs.room.runtime
    implementation libs.room.rxjava2
    kapt libs.room.compiler

    implementation libs.kotlin.stdlib.jdk8

    implementation libs.javax.inject
    implementation libs.rxjava
    implementation libs.rxkotlin
    implementation libs.retrofit
    implementation libs.jspoon
    implementation libs.gson

    testImplementation libs.junit
}
